version: "3.8"

services:
  db:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-express-app
    environment:
      PG_USER: postgres
      PG_PASSWORD: secret
      PG_DB: authdb
      PG_HOST: db
      PG_PORT: 5432
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  pgdata:
